"""update ar model

Revision ID: ed7dbd76a3ce
Revises: f3b1f6cb4766
Create Date: 2026-08-14 09:45:22.669954

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ed7dbd76a3ce"
down_revision: Union[str, Sequence[str], None] = "f3b1f6cb4766"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "armodels",
        "width",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=3),
        existing_nullable=False,
    )
    op.alter_column(
        "armodels",
        "height",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=3),
        existing_nullable=False,
    )
    op.alter_column(
        "armodels",
        "depth",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=3),
        existing_nullable=False,
    )
    op.alter_column(
        "armodels",
        "unit",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=1),
        existing_nullable=False,
    )
    op.create_check_constraint("ck_ar_models_depth_positive", "armodels", "depth > 0")
    op.create_check_constraint("ck_ar_models_height_positive", "armodels", "height > 0")
    op.create_check_constraint(
        "ck_ar_models_status", "armodels", "status IN ('active', 'not_active')"
    )
    op.create_check_constraint("ck_ar_models_width_positive", "armodels", "width > 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_ar_models_width_positive", "armodels", type_="check")
    op.drop_constraint("ck_ar_models_status", "armodels", type_="check")
    op.drop_constraint("ck_ar_models_height_positive", "armodels", type_="check")
    op.drop_constraint("ck_ar_models_depth_positive", "armodels", type_="check")
    op.alter_column(
        "armodels",
        "unit",
        existing_type=sa.String(length=1),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.alter_column(
        "armodels",
        "depth",
        existing_type=sa.Numeric(precision=10, scale=3),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "armodels",
        "height",
        existing_type=sa.Numeric(precision=10, scale=3),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "armodels",
        "width",
        existing_type=sa.Numeric(precision=10, scale=3),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
