from datetime import datetime

from sqlalchemy import DateTime, String
from sqlalchemy.orm import Mapped, mapped_column


class VisitorAttributionMixin:
    first_touch_source: Mapped[str | None] = mapped_column(String(64))
    first_touch_campaign: Mapped[str | None] = mapped_column(String(255))
    first_touch_gclid: Mapped[str | None] = mapped_column(String(255))
    first_touch_gbraid: Mapped[str | None] = mapped_column(String(255))
    first_touch_wbraid: Mapped[str | None] = mapped_column(String(255))
    first_touch_utm_source: Mapped[str | None] = mapped_column(String(255))
    first_touch_utm_medium: Mapped[str | None] = mapped_column(String(255))
    first_touch_utm_campaign: Mapped[str | None] = mapped_column(String(255))
    first_touch_utm_content: Mapped[str | None] = mapped_column(String(255))
    first_touch_utm_term: Mapped[str | None] = mapped_column(String(255))
    first_touch_landing_page: Mapped[str | None] = mapped_column(String(2048))
    first_touch_referrer: Mapped[str | None] = mapped_column(String(2048))
    first_touch_occurred_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    first_touch_sales_channel_id: Mapped[str | None] = mapped_column(String(32))
    last_non_direct_source: Mapped[str | None] = mapped_column(String(64))
    last_non_direct_campaign: Mapped[str | None] = mapped_column(String(255))
    last_non_direct_gclid: Mapped[str | None] = mapped_column(String(255))
    last_non_direct_gbraid: Mapped[str | None] = mapped_column(String(255))
    last_non_direct_wbraid: Mapped[str | None] = mapped_column(String(255))
    last_non_direct_utm_source: Mapped[str | None] = mapped_column(String(255))
    last_non_direct_utm_medium: Mapped[str | None] = mapped_column(String(255))
    last_non_direct_utm_campaign: Mapped[str | None] = mapped_column(String(255))
    last_non_direct_utm_content: Mapped[str | None] = mapped_column(String(255))
    last_non_direct_utm_term: Mapped[str | None] = mapped_column(String(255))
    last_non_direct_landing_page: Mapped[str | None] = mapped_column(String(2048))
    last_non_direct_referrer: Mapped[str | None] = mapped_column(String(2048))
    last_non_direct_occurred_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_non_direct_sales_channel_id: Mapped[str | None] = mapped_column(String(32))


class AttributionSnapshotMixin:
    attr_first_touch_source: Mapped[str | None] = mapped_column(String(64))
    attr_first_touch_campaign: Mapped[str | None] = mapped_column(String(255))
    attr_first_touch_gclid: Mapped[str | None] = mapped_column(String(255))
    attr_first_touch_gbraid: Mapped[str | None] = mapped_column(String(255))
    attr_first_touch_wbraid: Mapped[str | None] = mapped_column(String(255))
    attr_first_touch_utm_source: Mapped[str | None] = mapped_column(String(255))
    attr_first_touch_utm_medium: Mapped[str | None] = mapped_column(String(255))
    attr_first_touch_utm_campaign: Mapped[str | None] = mapped_column(String(255))
    attr_first_touch_utm_content: Mapped[str | None] = mapped_column(String(255))
    attr_first_touch_utm_term: Mapped[str | None] = mapped_column(String(255))
    attr_first_touch_landing_page: Mapped[str | None] = mapped_column(String(2048))
    attr_first_touch_referrer: Mapped[str | None] = mapped_column(String(2048))
    attr_first_touch_occurred_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    attr_first_touch_sales_channel_id: Mapped[str | None] = mapped_column(String(32))
    attr_last_non_direct_source: Mapped[str | None] = mapped_column(String(64))
    attr_last_non_direct_campaign: Mapped[str | None] = mapped_column(String(255))
    attr_last_non_direct_gclid: Mapped[str | None] = mapped_column(String(255))
    attr_last_non_direct_gbraid: Mapped[str | None] = mapped_column(String(255))
    attr_last_non_direct_wbraid: Mapped[str | None] = mapped_column(String(255))
    attr_last_non_direct_utm_source: Mapped[str | None] = mapped_column(String(255))
    attr_last_non_direct_utm_medium: Mapped[str | None] = mapped_column(String(255))
    attr_last_non_direct_utm_campaign: Mapped[str | None] = mapped_column(String(255))
    attr_last_non_direct_utm_content: Mapped[str | None] = mapped_column(String(255))
    attr_last_non_direct_utm_term: Mapped[str | None] = mapped_column(String(255))
    attr_last_non_direct_landing_page: Mapped[str | None] = mapped_column(String(2048))
    attr_last_non_direct_referrer: Mapped[str | None] = mapped_column(String(2048))
    attr_last_non_direct_occurred_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    attr_last_non_direct_sales_channel_id: Mapped[str | None] = mapped_column(String(32))
